version: 0.2

phases:
  build:
    commands:
      - echo "Building the Lambda functions"
      # Add any build commands required for your Lambda functions here
  post_build:
    commands:
    #GOAT Boat Float
      - echo "Updating Lambda function code"
      - aws lambda update-function-code --function-name "index-photos" --zip-file "fileb://index-photos.zip"
      - aws lambda update-function-code --function-name "search-photos" --zip-file "fileb://search-photos.zip"