version: 0.2

phases:
  build:
    commands:
      - echo "Building the Lambda functions"
      # Add any build commands required for your Lambda functions here
      - cd index-photos
      - zip -r index-photos.zip .
      - mv index-photos.zip ..
      - cd ../search-photos
      - zip -r search-photos.zip .
      - mv search-photos.zip ..
      - cd ../
      # - zip deployment.zip index-photos.zip search-photos.zip
      # - aws s3 cp deployment.zip s3://cloudpipeline/P1
      - ls -al
  post_build:
    commands:
      - echo "Updating Lambda function code"
      - aws lambda update-function-code --function-name "index-photos" --zip-file "fileb://index-photos.zip"
      - aws lambda update-function-code --function-name "search-photos" --zip-file "fileb://search-photos.zip"
