version: 0.2

phases:
  build:
    commands:
      - echo "Building the Lambda functions"
      # Add any build commands required for your Lambda functions here
      - zip index-photos.zip index-photos
      - zip search-photos.zip search-photos
    artifacts:
      files:
        - index-photos.zip
        - search-photos.zip
      name:
        - deployment.zip
  post_build:
    commands:
    #GOAT Boat Float tote
      - echo "Updating Lambda function code"
      - unzip deployment.zip
      - aws lambda update-function-code --function-name "index-photos" --zip-file "fileb://index-photos.zip"
      - aws lambda update-function-code --function-name "search-photos" --zip-file "fileb://search-photos.zip"